dist: xenial
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
- pypy
- pypy3
install:
- travis_retry pip install -r requirements.txt
- travis_retry pip install coveralls
script:
- coverage run --source=jsonpointer tests.py
after_script:
- coveralls
sudo: false
addons:
  apt:
    packages:
    - pandoc
before_deploy:
- pip install -r requirements-dev.txt
deploy:
  provider: pypi
  user: skoegl
  password:
    secure: ppMhKu82oIig1INyiNkt9veOd5FUUIKFUXj2TzxMSdzPtzAhQnScJMGPEtPfH8MwXng/CtJiDWS6zJzRFsW/3Ch+JHPkOtxOfkopBs1t1SpCyqNPSvf6Zxh83Dg6Bq6+8GyVW1RPuNIGflsvzY2C3z5i79FQXwZd8EQlg7Vu0Wo=
  on:
    tags: true
  distributions: sdist bdist_wheel
